export const ON_QUANTITY_CHANGE = "ON_QUANTITY_CHANGE";
export const DELETE_ITEM_FROM_CART="DELETE_ITEM_FROM_CART";
export const ADD_ITEM_TO_CART="ADD_ITEM_TO_CART";
export const EMPTY_CART="EMPTY_CART";
export const SEARCH_LIST="SEARCH_LIST";

